#!/usr/bin/env bash

HUE=(-level 10%,100%,0.8)
EFFECT=(-scale 10% -scale 1000%)
IMAGE="$(mktemp).png"
SHOT=(import -window root)
DESKTOP=""

# move pipefail down as for some reason "convert -list font" returns 1
set -o pipefail
trap 'rm -f "$IMAGE"' EXIT
TEMP="$(getopt -o :hdpglt:f: -l desktop,help,listfonts,pixelate,greyscale,text:,font: --name "$0" -- "$@")"
eval set -- "$TEMP"

if "$SET" && [[ $# -gt 0 ]]; then
    SHOT=("$@");
fi

"${SHOT[@]}" "$IMAGE"

# get path where the script is located to find the lock icon
SCRIPTPATH=$(realpath "$0")
SCRIPTPATH=${SCRIPTPATH%/*}

VALUE="60" #brightness value to compare to

COLOR=$(convert "$IMAGE" -gravity center -crop 100x100+0+0 +repage -colorspace hsb \
    -resize 1x1 txt:- | awk -F '[%$]' 'NR==2{gsub(",",""); printf "%.0f\n", $(NF-1)}');

if [ "$COLOR" -gt "$VALUE" ]; then #white background image and black text
    BW="black"
    ICON="$SCRIPTPATH/icons/lockdark.png"
    PARAM=(--textcolor=ff000000 --insidecolor=00000000 --ringcolor=00000000 \
        --linecolor=00000000 --keyhlcolor=ffffff00 --ringvercolor=ffffff00 \
        --separatorcolor=22222200 --insidevercolor=ffffff00 \
        --ringwrongcolor=ffffff00 --insidewrongcolor=ffffff00)
else #black
    BW="white"
    ICON="$SCRIPTPATH/icons/lock.png"
    PARAM=(--textcolor=ff000000 --insidecolor=ffffff00 --ringcolor=ffffff00 \
        --linecolor=ffffff00 --keyhlcolor=00000000 --ringvercolor=00000000 \
        --separatorcolor=22222200 --insidevercolor=00000000 \
        --ringwrongcolor=00000000 --insidewrongcolor=00000000)
fi

convert "$IMAGE" "${HUE[@]}" "${EFFECT[@]}" -font "$FONT" -pointsize 12 -fill "$BW" -gravity center\
    -annotate +0+160 "$TEXT" "$ICON" -gravity center -composite "$IMAGE"

# try to use a forked version of i3lock with prepared parameters
if ! i3lock -n "${PARAM[@]}" -i "$IMAGE" > /dev/null 2>&1; then
    # We have failed, lets get back to stock one
    i3lock -n -i "$IMAGE"
fi
